#数据源
source:
  #数据库驱动名称
  driver: mysql
  #数据库名称
  dbname: website
  #数据源名称
  dsn: root:123456@tcp(192.168.9.111:3306)/website
#生成的proto配置
proto:
  #生成的proto文件路径
  path: ./proto
  #生成的proto文件名称
  name: web_proto.proto
  #proto的header配置
  headers:
    - syntax = "proto3";
    - package model;
    - option go_package = "./model_proto;model";
    - import "common.proto";
    #- import \"google/protobuf/timestamp.proto\";
  #生成的proto对应model的前缀和后缀,示例表web_account，prefix=Test suffix=Model，则生成TestWebAccountModel的proto的message
  model:
    prefix: DB
    suffix: Model
#自定义数据源 对特定表的特定字段自定义类型
custom:
    #表名
  - table: web_account
    #表中的字段类型，优先级fields-> types
    types:
      datetime: int64
      date: int64
    #表中的特定字段
    fields:
        #表中的字段名称
      - field: bind_at
        #表中的类型转成proto的类型
        type: int64
      - field: created_at
        type: int64
      - field: updated_at
        type: int64
  - table: web_index_config
    types:
      datetime: int64
      date: int64
    fields:
      - field: channels
        type: repeated ChannelElem


